### ISSUE TITLE
Reserve Css for the stylesheet

### ISSUE THREAD

**Issue by tommygebru** [ansamshaik/prj-rev-bwfs-dasmoto#4]
https://github.com/ansamshaik/prj-rev-bwfs-dasmoto/blob/d67d012d3ad71b16ccfb8992421912edae0b3e78/Dasmoto's%20Arts%20%26%20Crafts/index.html#L18

While there is no issue with applying multiple _inline-styles_ it becomes easier to manage if written once and applied to the css selector in the css stylesheet.

p within div {change the css} _//written once, applied everywhere_

**Comment by ansamshaik** [comment]
Hi there, im sorry didn't notice that i can replay to your comments before. for this one i was wondering since the style i want to apply is only for few words in the paragraph, how can i do that in css for a p div and it will only target those words?

**Comment by tommygebru** [comment]
Hey so to apply a style to all elements nested within other elements the syntax will look like:

`div p {}` therefore it will be written once, applied everywhere within the webpage

Also for even more practice you can play with this excellent resource 

https://flukeout.github.io/

**Comment by ansamshaik** [comment]
Thanks !
